#!/bin/sh

BUILD_DIR="./build"
mkdir -p "$BUILD_DIR"

SERVICES=(
  "database" 
  "api" 
)

PIDS=()
echo "🚀 Starting services..."
for SERVICE in "${SERVICES[@]}"; do
  echo "▶️ Running $SERVICE..."
  
  APP_PROJECT="elevator"
  APP_NAME="$SERVICE"
  APP_ENV="local"
  
  # Export env vars and run the service
  app_project="$APP_PROJECT" app_name="$APP_NAME" app_env="$APP_ENV" \
    "$BUILD_DIR/${SERVICE}_service" &
    
  PIDS+=($!)
done

# Handle shutdown properly
trap "echo '🛑 Stopping services...'; kill ${PIDS[*]}; kill $NATS_PID; docker-compose down; exit 0" SIGINT SIGTERM

# Wait for all services to finish
wait
