// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_cards

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardActivation struct {
	ID              int32            `json:"id"`
	CardID          int32            `json:"card_id"`
	ActivationStart pgtype.Date      `json:"activation_start"`
	ActivationEnd   pgtype.Date      `json:"activation_end"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}
