// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardActivation struct {
	ID              int32            `json:"id"`
	CardID          int32            `json:"card_id"`
	ActivationStart pgtype.Date      `json:"activation_start"`
	ActivationEnd   pgtype.Date      `json:"activation_end"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Device struct {
	ID          int32              `json:"id"`
	DeviceID    string             `json:"device_id"`
	Location    pgtype.Text        `json:"location"`
	InstalledAt pgtype.Timestamptz `json:"installed_at"`
	Active      pgtype.Bool        `json:"active"`
}

type User struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Deleted   pgtype.Bool        `json:"deleted"`
}
