// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_devices

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID          int32              `json:"id"`
	DeviceID    string             `json:"device_id"`
	Location    pgtype.Text        `json:"location"`
	InstalledAt pgtype.Timestamptz `json:"installed_at"`
	Active      pgtype.Bool        `json:"active"`
}
