// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository_models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	DeviceID     pgtype.Text      `json:"device_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Balance struct {
	ID        int32              `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	CardID    int32              `json:"card_id"`
	RideCost  pgtype.Numeric     `json:"ride_cost"`
	Balance   pgtype.Numeric     `json:"balance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Card struct {
	ID         int32              `json:"id"`
	CardID     string             `json:"card_id"`
	UserID     int32              `json:"user_id"`
	DeviceID   int32              `json:"device_id"`
	Active     pgtype.Bool        `json:"active"`
	Type       string             `json:"type"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	Deleted    pgtype.Bool        `json:"deleted"`
}

type CardActivation struct {
	ID              int32            `json:"id"`
	CardID          int32            `json:"card_id"`
	ActivationStart pgtype.Date      `json:"activation_start"`
	ActivationEnd   pgtype.Date      `json:"activation_end"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Charge struct {
	ID          int32              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID          int32              `json:"id"`
	DeviceID    string             `json:"device_id"`
	Location    pgtype.Text        `json:"location"`
	InstalledAt pgtype.Timestamptz `json:"installed_at"`
	Active      pgtype.Bool        `json:"active"`
}

type PayboxTransaction struct {
	ID            pgtype.UUID      `json:"id"`
	CardID        int32            `json:"card_id"`
	Amount        float64          `json:"amount"`
	Source        pgtype.Text      `json:"source"`
	TransactionID pgtype.Text      `json:"transaction_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Trip struct {
	ID        int32              `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	CardID    pgtype.Int4        `json:"card_id"`
	DeviceID  string             `json:"device_id"`
	Floor     pgtype.Int4        `json:"floor"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

type User struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	PinCode   pgtype.Text        `json:"pin_code"`
	Deleted   pgtype.Bool        `json:"deleted"`
}
