// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package repository_models

import (
	"context"
)

const pingDB = `-- name: PingDB :one
SELECT 1
`

func (q *Queries) PingDB(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDB)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
